{{- if .Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datapipe.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "datapipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
data:
  {{- if .Values.database.password }}
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}
{{- end }}
